### ISSUE TITLE
not working on dotnet 7.0

### ISSUE THREAD

**Issue by Blaaac** [ShapourNemati/laurea-fradente#2]
i tried running it with dotnet 7.0 installed but i receive the following error:
`trashware@trashware-pc:~/laurea-fradente/brotooth.alwayspresent$ dotnet run
You must install or update .NET to run this application.

App: /home/trashware/laurea-fradente/brotooth.alwayspresent/bin/Debug/net6.0/brotooth.alwayspresent
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /usr/share/dotnet

The following frameworks were found:
  7.0.4 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=linuxmint.21-x64
`

**Comment by Blaaac** [comment]
installing dotnet 6.0 from ubuntu repo fixed the issue

**Comment by ShapourNemati** [comment]
There is no issue here, we just prefer well tested frameworks, and .net 6 provides us with the most stable version yet.
Using .net 7 with this project is highly discouraged.
To be honest, though, this could be added in the documentation. Feel free to open a PR.
Stay damp
